name: Talk the walked, Walk the talked
description:  My mind dump

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://stevegocoding.github.io
permalink: /:year/:month/:title/
owner:
    name: Guangfu Shi
    twitter: stevegocoding
    github: stevegocoding
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Canada/Eastern
